update upgrade env rule, now it uses project.config.orig for creating patch

diff --git a/.duckwizard/Makefile b/.duckwizard/Makefile
--- a/.duckwizard/Makefile
+++ b/.duckwizard/Makefile
@@ -398,42 +398,45 @@ update-files:
 	.duckwizard/scripts/restore_config $(CONFIG_FILE) project.config && \
 	cd .. && rm -rf .dw-temp-update
 
-#H# upgrade-env         : Upgrade the duckWizard environment using diff3 for project.config merge (replaces "make update-files")
+#H# upgrade-env         : Upgrade the duckWizard environment (replaces "make update-files")
 upgrade-env:
-	@echo -e "$(_info_)[INFO] Upgrading duckWizard environment...$(_reset_)"
-	@if [ -d duckwizard ]; then \
-		echo -e "$(_info_)[INFO] Updating the duckWizard repository...$(_reset_)"; \
-		cd duckwizard && git pull; \
+	@echo -e "$(_info_)[INFO] Upgrading duckWizard environment$(_reset_)"
+	@if [ ! -d duckwizard ]; then \
+		echo -e "$(_info_)[INFO] Cloning the duckWizard repository$(_reset_)"; \
+		git clone https://github.com/m4j0rt0m/duckwizard.git -b tmp/test-upgrade duckwizard; \
+		echo "NEW_DUCKWIZARD=1" > .duckwizard_created.tmp; \
 	else \
-		echo -e "$(_info_)[INFO] Cloning the duckWizard repository...$(_reset_)"; \
-		git clone https://github.com/m4j0rt0m/duckwizard.git -b tmp/test-upgrade; \
+		echo -e "$(_info_)[INFO] Updating the duckWizard repository$(_reset_)"; \
+		cd duckwizard && git pull; \
 	fi
-	@echo -e "$(_info_)[INFO] Merging project.config...$(_reset_)"
+	@echo -e "$(_info_)[INFO] Backing up the current project.config$(_reset_)"
 	@if [ -f project.config ]; then \
-		echo -e "$(_info_)[INFO] Backing up the current project.config...$(_reset_)"; \
 		cp project.config project.config.bak; \
-		if [ ! -f project.config.orig ]; then \
-			echo -e "$(_info_)[INFO] No original base config found. Using the current config as the base...$(_reset_)"; \
-			cp project.config project.config.orig; \
-		fi; \
-		echo -e "$(_info_)[INFO] Performing three-way merge of project.config...$(_reset_)"; \
-		diff3 -m project.config project.config.orig duckwizard/project.config > merged_project.config || true; \
+		echo -e "$(_info_)[INFO] Performing three-way merge of project.config$(_reset_)"; \
+		diff3 -m project.config $(CONFIG_ORIG_FILE) duckwizard/project.config > merged_project.config || true; \
 		if grep -q '<<<<<<<' merged_project.config; then \
 			echo -e "$(_info_)[INFO] Merge conflicts detected in project.config. Please manually resolve them in project.config.conflicted.$(_reset_)"; \
 			mv merged_project.config project.config.conflicted; \
 		else \
 			mv merged_project.config project.config; \
 			echo -e "$(_info_)[INFO] Merge complete. Updated project.config has been saved.$(_reset_)"; \
+			cp project.config $(CONFIG_ORIG_FILE); \
+			echo -e "$(_info_)[INFO] Updated $(CONFIG_ORIG_FILE) for future upgrades.$(_reset_)"; \
+			rm project.config.bak; \
 		fi; \
 	else \
-		echo -e "$(_info_)[INFO] No existing project.config found. Copying the new one from duckWizard.$(_reset_)"; \
+		echo -e "$(_info_)[INFO] No project.config found. Copying the new one from duckWizard.$(_reset_)"; \
 		cp duckwizard/project.config .; \
 	fi
-	@echo -e "$(_info_)[INFO] Ensuring all required directories are present...$(_reset_)"
+	@if [ -f .duckwizard_created.tmp ]; then \
+		echo -e "$(_info_)[INFO] Removing temporary duckWizard repository$(_reset_)"; \
+		rm -rf duckwizard; \
+		rm .duckwizard_created.tmp; \
+	fi
+	@echo -e "$(_info_)[INFO] Ensuring all required directories are present$(_reset_)"
 	@mkdir -p src/rtl src/include src/mem src/package
 	@mkdir -p tb/rtl tb/include tb/mem tb/package tb/scripts tb/cxx
-	@mkdir -p build
-	@echo -e "$(_info_)[INFO] Environment upgrade complete!$(_reset_)"
+	@echo -e "$(_info_)[INFO] duckWizard environment upgrade complete!$(_reset_)"
 
 #H# help                : Display help
 help: $(DUCKWIZARD_DIR)/Makefile $(SCRIPTS_DIR)/misc.mk
